- name: create ansible user
  user:
    name: "{{ansible_username}}"
    password: "{{ ansible_password | password_hash('sha512') }}"
    groups: wheel
    append: true
    generate_ssh_key: true
    ssh_key_comment: "{{ansible_username}}@{{ansible_facts['fqdn']}}"
  changed_when: false
- name: enable sudo without password
  copy:
    content: "{{ansible_username}} ALL=(ALL:ALL) NOPASSWD: ALL\n"
    dest: /etc/sudoers.d/{{ansible_username}}